package tui

import (
	"encoding/json"
	"json-type-builder/reader"
	"os"
	"strings"

	"github.com/atotto/clipboard"
	"github.com/charmbracelet/bubbles/textarea"
	"github.com/charmbracelet/bubbles/textinput"
	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

type model struct {
	reader     reader.JSONReader
	typeName   textinput.Model
	jsonInput  textarea.Model
	outputView viewport.Model
	fileInput  textinput.Model

	flags     reader.TagType
	err       string
	showPopup bool
	width     int
	height    int
}

func InitialModel() model {
	tn := textinput.New()
	tn.Placeholder = "Struct Name (e.g. User)"
	tn.Focus()

	ta := textarea.New()
	ta.Placeholder = "Paste JSON here..."
	ta.SetHeight(10)

	vp := viewport.New(0, 0)
	vp.SetContent("Go struct will appear here...")

	fi := textinput.New()
	fi.Placeholder = "path/to/file.json"

	return model{
		typeName:   tn,
		jsonInput:  ta,
		outputView: vp,
		fileInput:  fi,
		flags:      0,
	}
}

func (m model) Init() tea.Cmd {
	return textarea.Blink
}

func (m *model) processJSON() {
	input := m.jsonInput.Value()
	if strings.TrimSpace(input) == "" {
		m.outputView.SetContent("Waiting for input...")
		return
	}

	var rawData interface{}
	dec := json.NewDecoder(strings.NewReader(input))
	dec.UseNumber()

	if err := dec.Decode(&rawData); err != nil {
		m.err = "Invalid JSON: " + err.Error()
		return
	}

	if !m.jsonInput.Focused() {
		pretty, _ := json.MarshalIndent(rawData, "", "    ")
		m.jsonInput.SetValue(string(pretty))
	}

	m.err = ""
	name := m.typeName.Value()
	if name == "" {
		name = "AutoGenerated"
	}

	res := m.reader.ParseJSON(name, rawData, m.flags)
	m.outputView.SetContent(res)
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmds []tea.Cmd

	switch msg := msg.(type) {
	case tea.KeyMsg:
		if m.showPopup {
			switch msg.String() {
			case "esc":
				m.showPopup = false
				return m, nil
			case "enter":
				content, err := os.ReadFile(m.fileInput.Value())
				if err == nil {
					m.jsonInput.SetValue(string(content))
					m.showPopup = false
					m.processJSON()
				} else {
					m.err = "File Error: " + err.Error()
				}
				return m, nil
			}
			var cmd tea.Cmd
			m.fileInput, cmd = m.fileInput.Update(msg)
			return m, cmd
		}

		switch msg.String() {
		case "ctrl+c", "q":
			return m, tea.Quit
		case "U": // SHIFT+U
			m.showPopup = true
			m.fileInput.Focus()
			return m, nil
		case "ctrl+s":
			clipboard.WriteAll(m.outputView.View())
			return m, nil
		case "f1":
			m.flags ^= reader.TagMongo
			m.processJSON()
		case "f2":
			m.flags ^= reader.TagAWS
			m.processJSON()
		case "f3":
			m.flags ^= reader.TagProto
			m.processJSON()
		case "tab", "shift+tab":
			var cmd tea.Cmd
			if m.typeName.Focused() {
				m.typeName.Blur()
				cmd = m.jsonInput.Focus()
			} else {
				m.jsonInput.Blur()
				cmd = m.typeName.Focus()
			}
			return m, cmd
		}

	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
		m.jsonInput.SetWidth(msg.Width - 6)
		m.outputView.Width = msg.Width - 6
		m.outputView.Height = msg.Height / 3
	}

	if !m.showPopup {
		var cmd tea.Cmd
		m.typeName, cmd = m.typeName.Update(msg)
		cmds = append(cmds, cmd)

		prevJSON := m.jsonInput.Value()
		m.jsonInput, cmd = m.jsonInput.Update(msg)
		cmds = append(cmds, cmd)

		if m.jsonInput.Value() != prevJSON || m.typeName.Focused() {
			m.processJSON()
		}
	}

	return m, tea.Batch(cmds...)
}

var (
	titleStyle = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("#00ADD8"))
	errorStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("#FF0000")).Padding(0, 1)
	boxStyle   = lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).Padding(0, 1)
	tagStyle   = lipgloss.NewStyle().Background(lipgloss.Color("#3C3C3C")).Foreground(lipgloss.Color("#DDD")).Padding(0, 1).MarginRight(1)
	activeTag  = tagStyle.Copy().Background(lipgloss.Color("#008000")).Foreground(lipgloss.Color("#FFF"))
	popupStyle = lipgloss.NewStyle().Border(lipgloss.DoubleBorder()).Padding(1, 2).BorderForeground(lipgloss.Color("#00ADD8"))
)

func (m model) View() string {
	if m.showPopup {
		content := lipgloss.JoinVertical(lipgloss.Center,
			"UPLOAD JSON FILE",
			m.fileInput.View(),
			"\n(Press Enter to load, Esc to cancel)",
		)
		return lipgloss.Place(m.width, m.height, lipgloss.Center, lipgloss.Center, popupStyle.Render(content))
	}

	header := lipgloss.JoinVertical(lipgloss.Left,
		titleStyle.Render("GO STRUCT GENERATOR"),
		"Type Name:",
		m.typeName.View(),
	)

	var middle string
	if m.err != "" {
		middle = errorStyle.Render("❌ " + m.err)
	} else {
		middle = lipgloss.JoinHorizontal(lipgloss.Left,
			m.renderTag("F1: Mongo", m.flags&reader.TagMongo != 0),
			m.renderTag("F2: AWS", m.flags&reader.TagAWS != 0),
			m.renderTag("F3: Proto", m.flags&reader.TagProto != 0),
		)
	}

	layout := lipgloss.JoinVertical(lipgloss.Left,
		header,
		"\nJSON Input (Scrollable):",
		boxStyle.Render(m.jsonInput.View()),
		"\n"+middle,
		"\nGo Struct Output (CTRL+S to Copy):",
		boxStyle.Render(m.outputView.View()),
		"\n[Q] Quit | [Shift+U] Load File",
	)

	return lipgloss.NewStyle().Padding(1, 2).Render(layout)
}

func (m model) renderTag(label string, active bool) string {
	if active {
		return activeTag.Render(label)
	}
	return tagStyle.Render(label)
}
