package reader

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

type JSONReader struct {
}

type TagType int

const (
	TagMongo TagType = 1 << iota
	TagAWS
	TagProto
)

func (r JSONReader) getMongoTag(key string) string { return fmt.Sprintf("bson:\"%s\"", key) }
func (r JSONReader) getAWSTag(key string) string   { return fmt.Sprintf("dynamodbav:\"%s\"", key) }
func (r JSONReader) getProtoTag(key string, index int, pType string) string {
	return fmt.Sprintf("protobuf:\"%s,%d,opt,name=%s\"", pType, index, key)
}

func (r JSONReader) toPascalCase(s string) string {
	if s == "" {
		return ""
	}
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			r := []rune(part)
			r[0] = unicode.ToUpper(r[0])
			parts[i] = string(r)
		}
	}
	return strings.Join(parts, "")
}

func (r JSONReader) generateStructField(key string, goType string, protoType string, index int, flags TagType) string {
	fieldName := r.toPascalCase(key)
	tags := []string{fmt.Sprintf("json:\"%s\"", key)}

	if flags&TagMongo != 0 {
		tags = append(tags, r.getMongoTag(key))
	}
	if flags&TagAWS != 0 {
		tags = append(tags, r.getAWSTag(key))
	}
	if flags&TagProto != 0 {
		tags = append(tags, r.getProtoTag(key, index, protoType))
	}

	return fmt.Sprintf("    %s %s `%s`", fieldName, goType, strings.Join(tags, " "))
}

func (r JSONReader) ParseJSON(structName string, data interface{}, flags TagType) string {
	var sb strings.Builder
	if structName == "" {
		structName = "AutoGenerated"
	}

	r.parseRecursive(&sb, structName, data, "", 1, flags, true)
	return sb.String()
}

func (r JSONReader) parseRecursive(sb *strings.Builder, structName string, data interface{}, keyName string, index int, flags TagType, isRoot bool) {
	switch v := data.(type) {

	case map[string]interface{}:
		typeName := r.toPascalCase(keyName)
		if isRoot {
			sb.WriteString(fmt.Sprintf("type %s struct {\n", structName))
		} else {
			sb.WriteString(r.generateStructField(keyName, typeName, "message", index, flags) + "\n")
			sb.WriteString(fmt.Sprintf("\ntype %s struct {\n", typeName))
		}

		i := 1
		for k, val := range v {
			r.parseRecursive(sb, "", val, k, i, flags, false)
			i++
		}
		sb.WriteString("}\n")

	case []interface{}:
		if len(v) > 0 {
			switch first := v[0].(type) {
			case map[string]interface{}:
				singularName := strings.TrimSuffix(r.toPascalCase(keyName), "s")
				sb.WriteString(r.generateStructField(keyName, "[]"+singularName, "bytes", index, flags) + "\n")
				r.parseRecursive(sb, "", first, keyName, 1, flags, false)
			default:
				sb.WriteString(r.generateStructField(keyName, "[]any", "fixed64", index, flags) + "\n")
			}
		}

	case json.Number:
		goType, protoType := "int64", "int64"
		if strings.Contains(v.String(), ".") {
			goType, protoType = "float64", "double"
		}
		sb.WriteString(r.generateStructField(keyName, goType, protoType, index, flags) + "\n")

	case string:
		sb.WriteString(r.generateStructField(keyName, "string", "string", index, flags) + "\n")

	case bool:
		sb.WriteString(r.generateStructField(keyName, "bool", "bool", index, flags) + "\n")

	case nil:
		sb.WriteString(r.generateStructField(keyName, "*any", "bytes", index, flags) + "\n")
	}
}
