package reader

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

type JSONReader struct{}

type TagType int

const (
	TagMongo TagType = 1 << iota
	TagAWS
	TagProto
)

func (r JSONReader) getMongoTag(key string) string { return fmt.Sprintf("bson:\"%s\"", key) }
func (r JSONReader) getAWSTag(key string) string   { return fmt.Sprintf("dynamodbav:\"%s\"", key) }
func (r JSONReader) getProtoTag(key string, index int, pType string) string {
	return fmt.Sprintf("protobuf:\"%s,%d,opt,name=%s\"", pType, index, key)
}

func (r JSONReader) toPascalCase(s string) string {
	if s == "" {
		return ""
	}
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			r := []rune(part)
			r[0] = unicode.ToUpper(r[0])
			parts[i] = string(r)
		}
	}
	return strings.Join(parts, "")
}

func (r JSONReader) generateStructField(key string, goType string, protoType string, index int, flags TagType) string {
	fieldName := r.toPascalCase(key)
	tags := []string{fmt.Sprintf("json:\"%s\"", key)}

	if flags&TagMongo != 0 {
		tags = append(tags, r.getMongoTag(key))
	}
	if flags&TagAWS != 0 {
		tags = append(tags, r.getAWSTag(key))
	}
	if flags&TagProto != 0 {
		tags = append(tags, r.getProtoTag(key, index, protoType))
	}

	return fmt.Sprintf("    %s %s `%s`", fieldName, goType, strings.Join(tags, " "))
}

func (r JSONReader) ParseJSON(structName string, data interface{}, flags TagType) string {
	if structName == "" {
		structName = "AutoGenerated"
	}

	var allStructs []string

	switch v := data.(type) {
	case map[string]interface{}:
		r.buildStruct(structName, v, flags, &allStructs)
	case []interface{}:
		if len(v) > 0 {
			if m, ok := v[0].(map[string]interface{}); ok {
				r.buildStruct(structName, m, flags, &allStructs)
			}
		}
	}

	for i, j := 0, len(allStructs)-1; i < j; i, j = i+1, j-1 {
		allStructs[i], allStructs[j] = allStructs[j], allStructs[i]
	}

	return strings.Join(allStructs, "\n\n")
}

func (r JSONReader) buildStruct(name string, m map[string]interface{}, flags TagType, allStructs *[]string) {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("type %s struct {\n", name))

	i := 1
	for k, val := range m {
		goType, protoType := r.getTypeInfo(k, val, flags, allStructs)
		sb.WriteString(r.generateStructField(k, goType, protoType, i, flags) + "\n")
		i++
	}
	sb.WriteString("}")

	*allStructs = append(*allStructs, sb.String())
}

func (r JSONReader) getTypeInfo(key string, data interface{}, flags TagType, allStructs *[]string) (string, string) {
	switch v := data.(type) {
	case map[string]interface{}:
		typeName := r.toPascalCase(key)
		r.buildStruct(typeName, v, flags, allStructs)
		return typeName, "message"

	case []interface{}:
		if len(v) > 0 {
			switch first := v[0].(type) {
			case map[string]interface{}:
				singularName := strings.TrimSuffix(r.toPascalCase(key), "s")
				r.buildStruct(singularName, first, flags, allStructs)
				return "[]" + singularName, "bytes"
			default:
				return "[]any", "fixed64"
			}
		}
		return "[]any", "fixed64"

	case json.Number:
		if strings.Contains(v.String(), ".") {
			return "float64", "double"
		}
		return "int64", "int64"

	case string:
		return "string", "string"

	case bool:
		return "bool", "bool"

	default:
		return "*any", "bytes"
	}
}
